workflows:
  version: 2.1
  build:
    jobs:
      - unit-test-plugin:
          context:
            - unreal-engine-ci
          matrix:
            parameters:
              unreal-engine-version: ["5.1.0"]
              version: ["full"]
      - build-plugin:
          context:
            - unreal-engine-ci
          matrix:
            parameters:
              unreal-engine-version: ["4.27.0", "5.0.0", "5.1.0"]
              version: ["free", "full"]
      - build-sample:
          context:
            - unreal-engine-ci
          matrix:
            parameters:
              unreal-engine-version: ["5.0.0"]
              version: ["full"]

version: 2.1
jobs:
  unit-test-plugin:
    parameters:
      unreal-engine-version:
        type: string
      version:
        type: string
    docker:
      - image: ghcr.io/epicgames/unreal-engine:dev-slim-<< parameters.unreal-engine-version >>
        auth:
          username: $GHCR_USERNAME
          password: $GHCR_PASSWORD
    steps:
      - checkout
      - run:
          name: Run scripts for the license removing
          command: bash tools/remove_license.sh SamplePlugin << parameters.version >>
      - run:
          name: Run scripts for the code removing
          command: bash tools/remove_code.sh SamplePlugin << parameters.unreal-engine-version >> << parameters.version >> .
      - run:
          name: "Run scripts for the release"
          command: bash tools/replace_engine_version.sh SamplePlugin << parameters.unreal-engine-version >>
      - run:
          name: "Build Plugin"
          command: |
            /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh BuildPlugin \
              -Plugin=${PWD}/SamplePlugin/SamplePlugin.uplugin \
              -Package=/tmp/SamplePlugin \
              -Rocket
      - run:
          name: "Copy plugin"
          command: |
            mkdir ${PWD}/tests/unit_tests/UnitTestProejct/Plugins
            cp -r /tmp/SamplePlugin ${PWD}/tests/unit_tests/UnitTestProejct/Plugins
      - run:
          name: "Unit test against Plugin"
          command: |
            /home/ue4/UnrealEngine/Engine/Binaries/Linux/UnrealEditor \
              ${PWD}/tests/unit_tests/UnitTestProejct/UnitTestProejct.uproject \
              -unattended \
              -nopause \
              -NullRHI \
              -ExecCmds="Automation RunTests UnitTestExample" \
              -testexit="Automation Test Queue Empty" \
              -log=RunTests.log \
              -ReportOutputPath="/tmp/UnitTestsReport"

  build-plugin:
    parameters:
      unreal-engine-version:
        type: string
      version:
        type: string
    docker:
      - image: ghcr.io/epicgames/unreal-engine:dev-slim-<< parameters.unreal-engine-version >>
        auth:
          username: $GHCR_USERNAME
          password: $GHCR_PASSWORD
    steps:
      - checkout
      - run:
          name: Run scripts for the license removing
          command: bash tools/remove_license.sh SamplePlugin << parameters.version >>
      - run:
          name: Run scripts for the code removing
          command: bash tools/remove_code.sh SamplePlugin << parameters.unreal-engine-version >> << parameters.version >> .
      - run:
          name: "Run scripts for the release"
          command: bash tools/replace_engine_version.sh SamplePlugin << parameters.unreal-engine-version >>
      - run:
          name: "Build Plugin"
          command: |
            /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh BuildPlugin \
              -Plugin=${PWD}/SamplePlugin/SamplePlugin.uplugin \
              -Package=/tmp \
              -Rocket

  build-sample:
    parameters:
      unreal-engine-version:
        type: string
      version:
        type: string
    docker:
      - image: ghcr.io/epicgames/unreal-engine:dev-slim-<< parameters.unreal-engine-version >>
        auth:
          username: $GHCR_USERNAME
          password: $GHCR_PASSWORD
    steps:
      - checkout
      - run:
          name: Run scripts for the license removing
          command: bash tools/remove_license.sh SamplePlugin << parameters.version >>
      - run:
          name: Run scripts for the code removing
          command: bash tools/remove_code.sh SamplePlugin << parameters.unreal-engine-version >> << parameters.version >> .
      - run:
          name: "Run scripts for the release"
          command: bash tools/replace_engine_version.sh SamplePlugin << parameters.unreal-engine-version >>
      - run:
          name: "Copy plugin sources"
          command: |
            mkdir ${PWD}/samples/SampleProject/Plugins
            cp -r SamplePlugin ${PWD}/samples/SampleProject/Plugins
      - run:
          name: "Build Sample"
          command: |
            /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh BuildCookRun \
              -utf8output \
              -platform=Linux \
              -clientconfig=Shipping \
              -serverconfig=Shipping \
              -project=${PWD}/samples/SampleProject/SampleProject.uproject \
              -noP4 \
              -nodebuginfo \
              -allmaps \
              -cook \
              -build \
              -stage \
              -prereqs \
              -pak \
              -archive \
              -archivedirectory=/tmp/Packaged
